version: '3.8'

services:
  web:
    build: .
    ports:
      - "5889:5889" # Map port 5889 (เปลี่ยนจาก 5886 เพื่อไม่ให้ Port ชนกันหากรันบน VM เดียวกัน)
    
    # --- เพิ่มการตั้งค่า Volumes ตรงนี้ ---
    volumes:
      - /home/admintlp/it-annoucement-tlp:/app
    # --------------------------------

    # ใช้ environment variables ในการตั้งค่า (สามารถเพิ่ม SECRET_KEY หรือ DB_PASSWORD ที่นี่ได้ในอนาคต)
    environment:
      - DEBUG=1
    # ตั้งค่าให้ log output แสดงผลทันที (ไม่ buffer)
    tty: true
    stdin_open: true
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
