# Generated by Django 5.1.4 on 2026-05-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=255)),
                ('operate_date', models.CharField(max_length=100)),
                ('operate_time', models.CharField(max_length=50)),
                ('user_operate', models.CharField(max_length=200)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
