# Generated by Django 5.1.4 on 2026-08-21 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_owner', models.CharField(max_length=255)),
                ('objectives', models.TextField()),
                ('contractor_company', models.CharField(blank=True, max_length=255, null=True)),
                ('main_responsible_person', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('usage_purpose', models.CharField(blank=True, choices=[('new', 'ติดตั้งใหม่ (New Installation)'), ('modify', 'เปลี่ยนแปลงแก้ไข (Modify change)')], max_length=50, null=True)),
                ('usage_type', models.CharField(blank=True, max_length=50, null=True)),
                ('app_type', models.CharField(blank=True, max_length=255, null=True)),
                ('infra_type', models.CharField(blank=True, max_length=255, null=True)),
                ('software_dev_test', models.CharField(blank=True, max_length=50, null=True)),
                ('database_change', models.CharField(blank=True, max_length=255, null=True)),
                ('documents_provided', models.CharField(blank=True, max_length=255, null=True)),
                ('other_documents', models.CharField(blank=True, max_length=255, null=True)),
                ('vm_count', models.IntegerField(blank=True, null=True)),
                ('require_public_ip', models.BooleanField(default=False)),
                ('domain_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu_vcore', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_gb', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_gb', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('ports', models.CharField(blank=True, max_length=255, null=True)),
                ('has_authentication', models.BooleanField(default=False)),
                ('access_type', models.CharField(blank=True, max_length=100, null=True)),
                ('require_https', models.BooleanField(default=False)),
                ('expected_traffic', models.CharField(blank=True, max_length=255, null=True)),
                ('dependencies', models.CharField(blank=True, max_length=255, null=True)),
                ('require_dr_ha', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='change_requests/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='announcements.changerequest')),
            ],
        ),
    ]
