# Generated by Django 5.1.4 on 2026-08-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_changerequest_changerequestattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='request_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
