# Generated by Django 5.1.4 on 2026-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_changerequest_request_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='approver_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='approver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='evaluator_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='evaluator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='requester_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='requester_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
