# Generated by Django 5.1.4 on 2026-08-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_changerequest_approver_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
