# Generated by Django 5.1.4 on 2026-08-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_alter_changerequest_additional_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='other_documents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
